In [131]:
import json
import pandas as pd
import numpy as np
#  built-in Python module for regular expressions: re
import re

In [132]:
file_dir = 'C://Users/ayesh/class/Movies-ETL/'

In [133]:
f'{file_dir}wikipedia-movies'

'C://Users/ayesh/class/Movies-ETL/wikipedia-movies'

In [134]:
with open(f'{file_dir}/wikipedia-movies.json', mode='r') as file:
    wiki_movies_raw = json.load(file)

In [135]:
len(wiki_movies_raw)

7311

In [136]:
# First 5 records
wiki_movies_raw[:5]

[{'url': 'https://en.wikipedia.org/wiki/The_Adventures_of_Ford_Fairlane',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0098987/',
  'title': 'The Adventures of Ford Fairlane',
  'Directed by': 'Renny Harlin',
  'Produced by': ['Steve Perry', 'Joel Silver'],
  'Screenplay by': ['David Arnott', 'James Cappe', 'Daniel Waters'],
  'Story by': ['David Arnott', 'James Cappe'],
  'Based on': ['Characters', 'by Rex Weiner'],
  'Starring': ['Andrew Dice Clay',
   'Wayne Newton',
   'Priscilla Presley',
   'Lauren Holly',
   'Morris Day',
   'Robert Englund',
   "Ed O'Neill"],
  'Narrated by': 'Andrew "Dice" Clay',
  'Music by': ['Cliff Eidelman', 'Yello'],
  'Cinematography': 'Oliver Wood',
  'Edited by': 'Michael Tronick',
  'Productioncompany ': 'Silver Pictures',
  'Distributed by': '20th Century Fox',
  'Release date': ['July 11, 1990', '(', '1990-07-11', ')'],
  'Running time': '102 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$20 million',
  'Box office': '$21.4 million'},
 {'url': 'https://en.wikipedia.org/wiki/After_Dark,_My_Sweet',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0098994/',
  'title': 'After Dark, My Sweet',
  'Directed by': 'James Foley',
  'Produced by': ['Ric Kidney', 'Robert Redlin'],
  'Screenplay by': ['James Foley', 'Robert Redlin'],
  'Based on': ['the novel', 'After Dark, My Sweet', 'by', 'Jim Thompson'],
  'Starring': ['Jason Patric',
   'Rachel Ward',
   'Bruce Dern',
   'George Dickerson'],
  'Music by': 'Maurice Jarre',
  'Cinematography': 'Mark Plummer',
  'Edited by': 'Howard E. Smith',
  'Productioncompany ': 'Avenue Pictures',
  'Distributed by': 'Avenue Pictures',
  'Release date': ['May 17, 1990',
   '(',
   '1990-05-17',
   ')',
   '(Cannes Film Market)',
   'August 24, 1990',
   '(',
   '1990-08-24',
   ')',
   '(United States)'],
  'Running time': '114 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$6 million',
  'Box office': '$2.7 million'},
 {'url': 'https://en.wikipedia.org/wiki/Air_America_(film)',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0099005/',
  'title': 'Air America',
  'Directed by': 'Roger Spottiswoode',
  'Produced by': 'Daniel Melnick',
  'Screenplay by': ['John Eskow', 'Richard Rush'],
  'Based on': ['Air America', 'by', 'Christopher Robbins'],
  'Starring': ['Mel Gibson',
   'Robert Downey Jr.',
   'Nancy Travis',
   'David Marshall Grant',
   'Lane Smith'],
  'Music by': 'Charles Gross',
  'Cinematography': 'Roger Deakins',
  'Edited by': ['John Bloom', 'Lois Freeman-Fox'],
  'Productioncompany ': ['Carolco Pictures', 'IndieProd Company'],
  'Distributed by': 'TriStar Pictures',
  'Release date': ['August 10, 1990', '(', '1990-08-10', ')'],
  'Running time': '113 minutes',
  'Country': 'United States',
  'Language': ['English', 'Lao'],
  'Budget': '$35 million',
  'Box office': '$57,718,089'},
 {'url': 'https://en.wikipedia.org/wiki/Alice_(1990_film)',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0099012/',
  'title': 'Alice',
  'Directed by': 'Woody Allen',
  'Produced by': 'Robert Greenhut',
  'Written by': 'Woody Allen',
  'Starring': ['Alec Baldwin',
   'Blythe Danner',
   'Judy Davis',
   'Mia Farrow',
   'William Hurt',
   'Keye Luke',
   'Joe Mantegna',
   'Bernadette Peters'],
  'Cinematography': 'Carlo Di Palma',
  'Edited by': 'Susan E. Morse',
  'Distributed by': 'Orion Pictures',
  'Release date': ['December 25, 1990', '(', '1990-12-25', ')'],
  'Running time': '106 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$12 million',
  'Box office': '$7,331,647'},
 {'url': 'https://en.wikipedia.org/wiki/Almost_an_Angel',
  'year': 1990,
  'imdb_link': 'https://www.imdb.com/title/tt0099018/',
  'title': 'Almost an Angel',
  'Directed by': 'John Cornell',
  'Produced by': 'John Cornell',
  'Written by': 'Paul Hogan',
  'Starring': ['Paul Hogan', 'Elias Koteas', 'Linda Kozlowski'],
  'Music by': 'Maurice Jarre',
  'Cinematography': 'Russell Boyd',
  'Edited by': 'David Stiven',
  'Distributed by': 'Paramount Pictures',
  'Release date': 'December 19, 1990',
  'Running time': '95 minutes',
  'Country': 'US',
  'Language': 'English',
  'Budget': '$25 million',
  'Box office': '$6,939,946 (USA)'}]

In [137]:
# Last 5 records
wiki_movies_raw[-5:]

[{'url': 'https://en.wikipedia.org/wiki/Holmes_%26_Watson',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt1255919/',
  'title': 'Holmes & Watson',
  'Directed by': 'Etan Cohen',
  'Produced by': ['Will Ferrell',
   'Adam McKay',
   'Jimmy Miller',
   'Clayton Townsend'],
  'Screenplay by': 'Etan Cohen',
  'Based on': ['Sherlock Holmes',
   'and',
   'Dr. Watson',
   'by',
   'Sir Arthur Conan Doyle'],
  'Starring': ['Will Ferrell',
   'John C. Reilly',
   'Rebecca Hall',
   'Rob Brydon',
   'Steve Coogan',
   'Ralph Fiennes'],
  'Music by': 'Mark Mothersbaugh',
  'Cinematography': 'Oliver Wood',
  'Edited by': 'Dean Zimmerman',
  'Productioncompanies ': ['Columbia Pictures',
   'Gary Sanchez Productions',
   'Mosaic Media Group',
   'Mimran Schur Pictures'],
  'Distributed by': 'Sony Pictures Releasing',
  'Release date': ['December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '90 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$42 million',
  'Box office': '$41.9 million'},
 {'url': 'https://en.wikipedia.org/wiki/Vice_(2018_film)',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt6266538/',
  'title': 'Vice',
  'Directed by': 'Adam McKay',
  'Produced by': ['Brad Pitt',
   'Dede Gardner',
   'Jeremy Kleiner',
   'Kevin J. Messick',
   'Will Ferrell',
   'Adam McKay'],
  'Written by': 'Adam McKay',
  'Starring': ['Christian Bale',
   'Amy Adams',
   'Steve Carell',
   'Sam Rockwell',
   'Tyler Perry',
   'Alison Pill',
   'Lily Rabe',
   'Jesse Plemons'],
  'Music by': 'Nicholas Britell',
  'Cinematography': 'Greig Fraser',
  'Edited by': 'Hank Corwin',
  'Productioncompany ': ['Plan B Entertainment',
   'Gary Sanchez Productions',
   'Annapurna Pictures'],
  'Distributed by': 'Mirror Releasing',
  'Release date': ['December 11, 2018',
   '(',
   '2018-12-11',
   ')',
   '(',
   'Samuel Goldwyn Theater',
   ')',
   'December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '132 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$60 million',
  'Box office': '$76.1 million'},
 {'url': 'https://en.wikipedia.org/wiki/On_the_Basis_of_Sex',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt4669788/',
  'title': 'On the Basis of Sex',
  'Directed by': 'Mimi Leder',
  'Produced by': 'Robert W. Cort',
  'Written by': 'Daniel Stiepleman',
  'Starring': ['Felicity Jones',
   'Armie Hammer',
   'Justin Theroux',
   'Sam Waterston',
   'Kathy Bates'],
  'Music by': 'Mychael Danna',
  'Cinematography': 'Michael Grady',
  'Edited by': 'Michelle Tesoro',
  'Productioncompanies ': ['Focus Features',
   '[1]',
   'Participant Media',
   '[1]',
   'Robert Cort Productions',
   '[1]',
   'Alibaba Pictures',
   '[2]'],
  'Distributed by': 'Focus Features',
  'Release date': ['November 8, 2018',
   '(',
   '2018-11-08',
   ')',
   '(',
   'AFI Fest',
   ')',
   'December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '120 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$20 million',
  'Box office': '$38.4 million'},
 {'url': 'https://en.wikipedia.org/wiki/Destroyer_(2018_film)',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt7137380/',
  'title': 'Destroyer',
  'Directed by': 'Karyn Kusama',
  'Produced by': ['Fred Berger', 'Phil Hay', 'Matt Manfredi'],
  'Written by': ['Phil Hay', 'Matt Manfredi'],
  'Starring': ['Nicole Kidman',
   'Sebastian Stan',
   'Toby Kebbell',
   'Tatiana Maslany',
   'Bradley Whitford',
   'Jade Pettyjohn',
   'Scoot McNairy'],
  'Music by': 'Theodore Shapiro',
  'Cinematography': 'Julie Kirkwood',
  'Edited by': 'Plummy Tucker',
  'Productioncompany ': ['30West',
   'Automatik Entertainment',
   'Annapurna Pictures'],
  'Distributed by': 'Mirror Releasing',
  'Release date': ['August 31, 2018',
   '(',
   '2018-08-31',
   ')',
   '(',
   'Telluride',
   ')',
   'December 25, 2018',
   '(',
   '2018-12-25',
   ')',
   '(United States)'],
  'Running time': '123 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$9 million',
  'Box office': '$5.5 million'},
 {'url': 'https://en.wikipedia.org/wiki/Black_Mirror:_Bandersnatch',
  'year': 2018,
  'imdb_link': 'https://www.imdb.com/title/tt9495224/',
  'title': 'Bandersnatch',
  'Directed by': 'David Slade',
  'Produced by': 'Russell McLean',
  'Written by': 'Charlie Brooker',
  'Starring': ['Fionn Whitehead',
   'Will Poulter',
   'Craig Parkinson',
   'Alice Lowe',
   'Asim Chaudhry'],
  'Music by': 'Brian Reitzell',
  'Cinematography': ['Aaron Morton', 'Jake Polonsky'],
  'Edited by': 'Tony Kearns',
  'Productioncompany ': ['House of Tomorrow', 'Netflix'],
  'Distributed by': 'Netflix',
  'Release date': ['28 December 2018', '(', '2018-12-28', ')'],
  'Running time': 'Variable; 90 minutes for default path',
  'Country': 'United Kingdom',
  'Language': 'English'}]

In [138]:
# Some records in the middle
wiki_movies_raw[3600:3605]

[{'url': 'https://en.wikipedia.org/wiki/Benji:_Off_the_Leash!',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0315273/',
  'title': 'Benji: Off the Leash!',
  'Directed by': 'Joe Camp',
  'Written by': 'Joe Camp',
  'Starring': ['Benji', 'Nick Whitaker', 'Shaggy', 'Gypsy the Cockatoo'],
  'Music by': 'Antonio di Lorenzo',
  'Productioncompany ': 'Mulberry Square Productions',
  'Distributed by': 'Mulberry Square Productions',
  'Release date': ['March 26, 2004', '(', '2004-03-26', ')'],
  'Running time': '97 min',
  'Country': 'United States',
  'Language': 'English',
  'Box office': '$3,817,362'},
 {'url': 'https://en.wikipedia.org/wiki/The_Best_Thief_in_the_World',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0389796/',
  'title': 'The Best Thief in the World',
  'Directed by': 'Jacob Kornbluth',
  'Produced by': ['Tim Perrell', 'Nicola Usborne'],
  'Written by': 'Jacob Kornbluth',
  'Starring': ['Marc Rozendaal',
   'Michael Silverman',
   'David Warshofsky',
   'Audra McDonald',
   'Lois Smith'],
  'Music by': ['Prince Paul', 'and', 'Don Newkirk'],
  'Cinematography': 'Ben Kutchins',
  'Edited by': 'Stephanie Sterner',
  'Distributed by': 'Showtime Networks',
  'Release date': ['January 16, 2004', '(', '2004-01-16', ')'],
  'Running time': '93 minutes',
  'Country': 'United States',
  'Language': 'English'},
 {'url': 'https://en.wikipedia.org/wiki/Beyond_the_Sea_(2004_film)',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0363473/',
  'title': 'Beyond the Sea',
  'Directed by': 'Kevin Spacey',
  'Produced by': ['Kevin Spacey',
   'Phillip Barry',
   'Dana Brunetti',
   'Arthur Friedman',
   'Jan Fantl',
   'Andy Paterson'],
  'Written by': ['Lewis Colick', 'Kevin Spacey'],
  'Starring': ['Kevin Spacey', 'Kate Bosworth', 'Bob Hoskins', 'John Goodman'],
  'Music by': 'Bobby Darin',
  'Cinematography': 'Eduardo Serra',
  'Edited by': 'Trevor Waite',
  'Productioncompany ': 'Trigger Street Productions',
  'Distributed by': ['Lionsgate Films',
   '(USA)',
   'Entertainment Film Distributors',
   '(UK)',
   'GAGA',
   '(Japan)',
   'Maple Pictures',
   '(Canada)'],
  'Release date': ['December 17, 2004', '(', '2004-12-17', ')'],
  'Running time': '118 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$25 million',
  'Box office': '$8.4 million'},
 {'url': 'https://en.wikipedia.org/wiki/The_Big_Bounce_(2004_film)',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0315824/',
  'title': 'The Big Bounce',
  'Directed by': 'George Armitage',
  'Produced by': ['George Armitage', 'Steve Bing'],
  'Screenplay by': 'Sebastian Gutierrez',
  'Based on': ['The Big Bounce', 'by', 'Elmore Leonard'],
  'Starring': ['Owen Wilson',
   'Charlie Sheen',
   'Morgan Freeman',
   'Sara Foster',
   'Gary Sinise'],
  'Music by': 'George S. Clinton',
  'Cinematography': 'Jeffrey L. Kimball',
  'Edited by': 'Barry Malkin',
  'Productioncompany ': 'Shangri-La Entertainment',
  'Distributed by': 'Warner Bros. Pictures',
  'Release date': ['January 30, 2004', '(', '2004-01-30', ')'],
  'Running time': '88 minutes',
  'Language': 'English',
  'Budget': '$50 million',
  'Box office': '$6.8 million'},
 {'url': 'https://en.wikipedia.org/wiki/Birth_(film)',
  'year': 2004,
  'imdb_link': 'https://www.imdb.com/title/tt0337876/',
  'title': 'Birth',
  'Directed by': 'Jonathan Glazer',
  'Produced by': ['Lizie Gower', 'Nick Morris', 'Jean-Louis Piel'],
  'Written by': ['Jean-Claude Carrière', 'Milo Addica', 'Jonathan Glazer'],
  'Starring': ['Nicole Kidman',
   'Cameron Bright',
   'Danny Huston',
   'Lauren Bacall'],
  'Music by': 'Alexandre Desplat',
  'Cinematography': 'Harris Savides',
  'Edited by': ['Sam Sneade', 'Claus Wehlisch'],
  'Distributed by': 'New Line Cinema',
  'Release date': ['November 8, 2004', '(', '2004-11-08', ')'],
  'Running time': '96 minutes',
  'Country': 'United States',
  'Language': 'English',
  'Budget': '$20 million',
  'Box office': '$23.9 million'}]

In [139]:
kaggle_metadata = pd.read_csv(f'{file_dir}movies_metadata.csv', low_memory=False)
ratings = pd.read_csv(f'{file_dir}ratings.csv')

In [140]:
kaggle_metadata.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,"373,554,033.00",81.00,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.70,"5,415.00"
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,"262,797,249.00",104.00,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.90,"2,413.00"
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.00,101.00,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.50,92.00
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,"81,452,156.00",127.00,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.10,34.00
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,"76,578,911.00",106.00,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.70,173.00

In [141]:
ratings.head()

   userId  movieId               rating   timestamp
0       1      110                 1.00  1425941529
1       1      147                 4.50  1425942435
2       1      858                 5.00  1425941523
3       1     1221                 5.00  1425941546
4       1     1246                 5.00  1425941556

In [142]:
kaggle_metadata.sample(n=5)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
23011,False,"{'id': 403001, 'name': 'Meu Passado me Condena...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,228202,tt3034258,pt,Meu Passado me Condena,The immature and cheap douche bag Fábio Clóvis...,...,2013-10-25,0.00,0.00,"[{'iso_639_1': 'pt', 'name': 'Português'}]",Released,NaN,Meu Passado me Condena,False,6.50,69.00
5891,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,18692,tt0057083,en,Fun in Acapulco,Mike works on a boat in Acapulco. When the bra...,...,1963-01-01,0.00,97.00,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Fun in Acapulco,False,5.80,15.00
11877,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 37, 'nam...",NaN,17660,tt0031235,en,Dodge City,Michael Curtiz's epic Western stars Errol Flyn...,...,1939-03-31,0.00,104.00,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It's Errol Flynn In His Greatest Role . . . A ...,Dodge City,False,6.70,17.00
5448,False,"{'id': 330555, 'name': 'Ernest Collection', 'p...",0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",NaN,18943,tt0099512,en,Ernest Goes to Jail,Bumbling Ernest P. Worrell is assigned to jury...,...,1990-04-06,0.00,81.00,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Guilty of Maximum Fun in the First Degree!,Ernest Goes to Jail,False,5.10,33.00
34393,False,NaN,5000000,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",NaN,51129,tt0403783,ru,Мастер и Маргарита,The Master and Margarita is a Russian TV mini-...,...,2005-12-19,0.00,500.00,"[{'iso_639_1': 'ru', 'name': 'Pусский'}]",Released,Manuscripts don't burn!,The Master and Margarita,False,6.20,9.00

In [143]:
# display all coloumns in list
kaggle_metadata.columns.to_list()

['adult',
 'belongs_to_collection',
 'budget',
 'genres',
 'homepage',
 'id',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'poster_path',
 'production_companies',
 'production_countries',
 'release_date',
 'revenue',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'video',
 'vote_average',
 'vote_count']

In [144]:
wiki_movies_df = pd.DataFrame(wiki_movies_raw)
wiki_movies_df.head()

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Predecessor,Founders,Area served,Products,Services,Russian,Hebrew,Revenue,Operating income,Polish
0,https://en.wikipedia.org/wiki/The_Adventures_o...,"1,990.00",https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,Renny Harlin,"[Steve Perry, Joel Silver]","[David Arnott, James Cappe, Daniel Waters]","[David Arnott, James Cappe]","[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...","1,990.00",https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet",James Foley,"[Ric Kidney, Robert Redlin]","[James Foley, Robert Redlin]",NaN,"[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://en.wikipedia.org/wiki/Air_America_(film),"1,990.00",https://www.imdb.com/title/tt0099005/,Air America,Roger Spottiswoode,Daniel Melnick,"[John Eskow, Richard Rush]",NaN,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://en.wikipedia.org/wiki/Alice_(1990_film),"1,990.00",https://www.imdb.com/title/tt0099012/,Alice,Woody Allen,Robert Greenhut,NaN,NaN,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://en.wikipedia.org/wiki/Almost_an_Angel,"1,990.00",https://www.imdb.com/title/tt0099018/,Almost an Angel,John Cornell,John Cornell,NaN,NaN,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [145]:
wiki_movies = [movie for movie in wiki_movies_raw
               if ('Director' in movie or 'Directed by' in movie)
                   and 'imdb_link' in movie]
len(wiki_movies)

7080

In [146]:
wiki_movies = [movie for movie in wiki_movies_raw
               if ('Director' in movie or 'Directed by' in movie)
                   and 'imdb_link' in movie
                   and 'No. of episodes' not in movie]
len(wiki_movies)

7076

In [147]:
wiki_movies_df=pd.DataFrame(wiki_movies)

In [148]:
def clean_movie(movie):
    movie = dict(movie) #create a non-destructive copy
    return movie

In [149]:
wiki_movies_df[wiki_movies_df['Arabic'].notnull()]

,url,year,imdb_link,title,Directed by,Produced by,Screenplay by,Story by,Based on,Starring,...,Hepburn,Literally,Cantonese,Chinese,Yiddish,Arabic,Romanized,Russian,Hebrew,Polish
6834,https://en.wikipedia.org/wiki/The_Insult_(film),2018,https://www.imdb.com/title/tt7048622/,The Insult,Ziad Doueiri,"[Rachid Bouchareb, Jean Bréhat, Julie Gayet, A...",NaN,NaN,NaN,"[Adel Karam, Kamel El Basha]",...,NaN,Case No. 23,NaN,NaN,NaN,قضية رقم ٢٣,Qadiyya raqm 23,NaN,NaN,NaN
7058,https://en.wikipedia.org/wiki/Capernaum_(film),2018,https://www.imdb.com/title/tt8267604/,Capernaum,Nadine Labaki,"[Michel Merkt, Khaled Mouzanar]","[Nadine Labaki, Jihad Hojaily, Michelle Keserw...","[Georges Khabbaz, Nadine Labaki, Michelle Kese...",NaN,"[Zain Al Rafeea, Yordanos Shiferaw, Boluwatife...",...,NaN,NaN,NaN,NaN,NaN,کفرناحوم‎,NaN,NaN,NaN,NaN

In [150]:
wiki_movies_df[wiki_movies_df['Arabic'].notnull()]['url']

6834    https://en.wikipedia.org/wiki/The_Insult_(film)
7058     https://en.wikipedia.org/wiki/Capernaum_(film)
Name: url, dtype: object

In [151]:
sorted(wiki_movies_df.columns.tolist())

['Adaptation by',
 'Also known as',
 'Animation by',
 'Arabic',
 'Audio format',
 'Based on',
 'Box office',
 'Budget',
 'Cantonese',
 'Chinese',
 'Cinematography',
 'Color process',
 'Composer(s)',
 'Country',
 'Country of origin',
 'Created by',
 'Directed by',
 'Director',
 'Distributed by',
 'Distributor',
 'Edited by',
 'Editor(s)',
 'Executive producer(s)',
 'Followed by',
 'French',
 'Genre',
 'Hangul',
 'Hebrew',
 'Hepburn',
 'Japanese',
 'Label',
 'Language',
 'Length',
 'Literally',
 'Mandarin',
 'McCune–Reischauer',
 'Music by',
 'Narrated by',
 'Original language(s)',
 'Original network',
 'Original release',
 'Original title',
 'Picture format',
 'Polish',
 'Preceded by',
 'Produced by',
 'Producer',
 'Producer(s)',
 'Production company(s)',
 'Production location(s)',
 'Productioncompanies ',
 'Productioncompany ',
 'Recorded',
 'Release date',
 'Released',
 'Revised Romanization',
 'Romanized',
 'Running time',
 'Russian',
 'Screen story by',
 'Screenplay by',
 'Simplified',
 'Starring',
 'Story by',
 'Suggested by',
 'Theme music composer',
 'Traditional',
 'Venue',
 'Voices of',
 'Written by',
 'Yiddish',
 'imdb_link',
 'title',
 'url',
 'year']

In [152]:
# Make an empty dict to hold all of the alternative titles.
def clean_movie(movie):
    movie = dict(movie) #create a non-destructive copy
    alt_titles = {}
    return movie

In [153]:
# Loop through a list of all alternative title keys.
def clean_movie(movie):
    movie = dict(movie) #create a non-destructive copy
    alt_titles = {}
    for key in ['Also known as','Arabic','Cantonese','Chinese','French',
                'Hangul','Hebrew','Hepburn','Japanese','Literally',
                'Mandarin','McCune–Reischauer','Original title','Polish',
                'Revised Romanization','Romanized','Russian',
                'Simplified','Traditional','Yiddish']:

        return movie

In [154]:
# Check if the current key exists in the movie object.
def clean_movie(movie):
    movie = dict(movie) #create a non-destructive copy
    alt_titles = {}
    for key in ['Also known as','Arabic','Cantonese','Chinese','French',
                'Hangul','Hebrew','Hepburn','Japanese','Literally',
                'Mandarin','McCune–Reischauer','Original title','Polish',
                'Revised Romanization','Romanized','Russian',
                'Simplified','Traditional','Yiddish']:
        if key in movie:

            return movie

In [155]:
# remove the key-value pair and add to the alternative titles dictionary.
def clean_movie(movie):
    movie = dict(movie) #create a non-destructive copy
    alt_titles = {}
    for key in ['Also known as','Arabic','Cantonese','Chinese','French',
                'Hangul','Hebrew','Hepburn','Japanese','Literally',
                'Mandarin','McCune–Reischauer','Original title','Polish',
                'Revised Romanization','Romanized','Russian',
                'Simplified','Traditional','Yiddish']:
        if key in movie:
            alt_titles[key] = movie[key]
            movie.pop(key)


    return movie

In [156]:
# After looping through every key, add the alternative titles dict to the movie object.
def clean_movie(movie):
    movie = dict(movie) #create a non-destructive copy
    alt_titles = {}
    for key in ['Also known as','Arabic','Cantonese','Chinese','French',
                'Hangul','Hebrew','Hepburn','Japanese','Literally',
                'Mandarin','McCune–Reischauer','Original title','Polish',
                'Revised Romanization','Romanized','Russian',
                'Simplified','Traditional','Yiddish']:
        if key in movie:
            alt_titles[key] = movie[key]
            movie.pop(key)
    if len(alt_titles) > 0:
        movie['alt_titles'] = alt_titles

    return movie

In [157]:
clean_movies = [clean_movie(movie) for movie in wiki_movies]
wiki_movies_df = pd.DataFrame(clean_movies)
sorted(wiki_movies_df.columns.tolist())

['Adaptation by',
 'Animation by',
 'Audio format',
 'Based on',
 'Box office',
 'Budget',
 'Cinematography',
 'Color process',
 'Composer(s)',
 'Country',
 'Country of origin',
 'Created by',
 'Directed by',
 'Director',
 'Distributed by',
 'Distributor',
 'Edited by',
 'Editor(s)',
 'Executive producer(s)',
 'Followed by',
 'Genre',
 'Label',
 'Language',
 'Length',
 'Music by',
 'Narrated by',
 'Original language(s)',
 'Original network',
 'Original release',
 'Picture format',
 'Preceded by',
 'Produced by',
 'Producer',
 'Producer(s)',
 'Production company(s)',
 'Production location(s)',
 'Productioncompanies ',
 'Productioncompany ',
 'Recorded',
 'Release date',
 'Released',
 'Running time',
 'Screen story by',
 'Screenplay by',
 'Starring',
 'Story by',
 'Suggested by',
 'Theme music composer',
 'Venue',
 'Voices of',
 'Written by',
 'alt_titles',
 'imdb_link',
 'title',
 'url',
 'year']

In [158]:
# consolidate columns with the same data into one column. We can use the pop() method to change the name of a dictionary key
def clean_movie(movie):
    movie = dict(movie) #create a non-destructive copy
    alt_titles = {}
    for key in ['Also known as','Arabic','Cantonese','Chinese','French',
                'Hangul','Hebrew','Hepburn','Japanese','Literally',
                'Mandarin','McCune–Reischauer','Original title','Polish',
                'Revised Romanization','Romanized','Russian',
                'Simplified','Traditional','Yiddish']:
        if key in movie:
            alt_titles[key] = movie[key]
            movie.pop(key)
    if len(alt_titles) > 0:
        movie['alt_titles'] = alt_titles
        
        # merge column names
    def change_column_name(old_name, new_name):
        if old_name in movie:
            movie[new_name] = movie.pop(old_name)
    change_column_name('Adaptation by', 'Writer(s)')
    change_column_name('Country of origin', 'Country')
    change_column_name('Directed by', 'Director')
    change_column_name('Distributed by', 'Distributor')
    change_column_name('Edited by', 'Editor(s)')
    change_column_name('Length', 'Running time')
    change_column_name('Original release', 'Release date')
    change_column_name('Music by', 'Composer(s)')
    change_column_name('Produced by', 'Producer(s)')
    change_column_name('Producer', 'Producer(s)')
    change_column_name('Productioncompanies ', 'Production company(s)')
    change_column_name('Productioncompany ', 'Production company(s)')
    change_column_name('Released', 'Release Date')
    change_column_name('Release Date', 'Release date')
    change_column_name('Screen story by', 'Writer(s)')
    change_column_name('Screenplay by', 'Writer(s)')
    change_column_name('Story by', 'Writer(s)')
    change_column_name('Theme music composer', 'Composer(s)')
    change_column_name('Written by', 'Writer(s)')

    return movie

In [159]:
clean_movies = [clean_movie(movie) for movie in wiki_movies]
wiki_movies_df = pd.DataFrame(clean_movies)
sorted(wiki_movies_df.columns.tolist())

['Animation by',
 'Audio format',
 'Based on',
 'Box office',
 'Budget',
 'Cinematography',
 'Color process',
 'Composer(s)',
 'Country',
 'Created by',
 'Director',
 'Distributor',
 'Editor(s)',
 'Executive producer(s)',
 'Followed by',
 'Genre',
 'Label',
 'Language',
 'Narrated by',
 'Original language(s)',
 'Original network',
 'Picture format',
 'Preceded by',
 'Producer(s)',
 'Production company(s)',
 'Production location(s)',
 'Recorded',
 'Release date',
 'Running time',
 'Starring',
 'Suggested by',
 'Venue',
 'Voices of',
 'Writer(s)',
 'alt_titles',
 'imdb_link',
 'title',
 'url',
 'year']

In [160]:
wiki_movies_df['imdb_id'] = wiki_movies_df['imdb_link'].str.extract(r'(tt\d{7})')
print(len(wiki_movies_df))

7076

In [161]:
wiki_movies_df.drop_duplicates(subset='imdb_id', inplace=True)
print(len(wiki_movies_df))

7033

In [162]:
wiki_movies_df.head()

,url,year,imdb_link,title,Based on,Starring,Narrated by,Cinematography,Release date,Running time,...,Created by,Preceded by,Suggested by,alt_titles,Recorded,Venue,Label,Animation by,Color process,imdb_id
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,"[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...","Andrew ""Dice"" Clay",Oliver Wood,"[July 11, 1990, (, 1990-07-11, )]",102 minutes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0098987
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet","[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",NaN,Mark Plummer,"[May 17, 1990, (, 1990-05-17, ), (Cannes Film ...",114 minutes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0098994
2,https://en.wikipedia.org/wiki/Air_America_(film),1990,https://www.imdb.com/title/tt0099005/,Air America,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",NaN,Roger Deakins,"[August 10, 1990, (, 1990-08-10, )]",113 minutes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0099005
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990,https://www.imdb.com/title/tt0099012/,Alice,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",NaN,Carlo Di Palma,"[December 25, 1990, (, 1990-12-25, )]",106 minutes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0099012
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990,https://www.imdb.com/title/tt0099018/,Almost an Angel,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",NaN,Russell Boyd,"December 19, 1990",95 minutes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tt0099018

In [163]:
[[column,wiki_movies_df[column].isnull().sum()] for column in wiki_movies_df.columns]

[['url', 0],
 ['year', 0],
 ['imdb_link', 0],
 ['title', 1],
 ['Based on', 4852],
 ['Starring', 184],
 ['Narrated by', 6752],
 ['Cinematography', 691],
 ['Release date', 32],
 ['Running time', 139],
 ['Country', 236],
 ['Language', 244],
 ['Budget', 2295],
 ['Box office', 1548],
 ['Director', 0],
 ['Distributor', 357],
 ['Editor(s)', 548],
 ['Composer(s)', 518],
 ['Producer(s)', 202],
 ['Production company(s)', 1678],
 ['Writer(s)', 199],
 ['Genre', 6923],
 ['Original language(s)', 6875],
 ['Original network', 6908],
 ['Executive producer(s)', 6936],
 ['Production location(s)', 6986],
 ['Picture format', 6969],
 ['Audio format', 6972],
 ['Voices of', 7031],
 ['Followed by', 7024],
 ['Created by', 7023],
 ['Preceded by', 7023],
 ['Suggested by', 7032],
 ['alt_titles', 7012],
 ['Recorded', 7031],
 ['Venue', 7032],
 ['Label', 7031],
 ['Animation by', 7031],
 ['Color process', 7032],
 ['imdb_id', 0]]

In [164]:
[column for column in wiki_movies_df.columns if wiki_movies_df[column].isnull().sum() < len(wiki_movies_df) * 0.9]

['url',
 'year',
 'imdb_link',
 'title',
 'Based on',
 'Starring',
 'Cinematography',
 'Release date',
 'Running time',
 'Country',
 'Language',
 'Budget',
 'Box office',
 'Director',
 'Distributor',
 'Editor(s)',
 'Composer(s)',
 'Producer(s)',
 'Production company(s)',
 'Writer(s)',
 'imdb_id']

In [165]:
#  make a list of columns that have less than 90% null values and use those to trim down dataset.
wiki_columns_to_keep = [column for column in wiki_movies_df.columns if wiki_movies_df[column].isnull().sum() < len(wiki_movies_df) * 0.9]
wiki_movies_df = wiki_movies_df[wiki_columns_to_keep]

In [166]:
wiki_movies_df.head()

,url,year,imdb_link,title,Based on,Starring,Cinematography,Release date,Running time,Country,...,Budget,Box office,Director,Distributor,Editor(s),Composer(s),Producer(s),Production company(s),Writer(s),imdb_id
0,https://en.wikipedia.org/wiki/The_Adventures_o...,1990,https://www.imdb.com/title/tt0098987/,The Adventures of Ford Fairlane,"[Characters, by Rex Weiner]","[Andrew Dice Clay, Wayne Newton, Priscilla Pre...",Oliver Wood,"[July 11, 1990, (, 1990-07-11, )]",102 minutes,United States,...,$20 million,$21.4 million,Renny Harlin,20th Century Fox,Michael Tronick,"[Cliff Eidelman, Yello]","[Steve Perry, Joel Silver]",Silver Pictures,"[David Arnott, James Cappe]",tt0098987
1,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",1990,https://www.imdb.com/title/tt0098994/,"After Dark, My Sweet","[the novel, After Dark, My Sweet, by, Jim Thom...","[Jason Patric, Rachel Ward, Bruce Dern, George...",Mark Plummer,"[May 17, 1990, (, 1990-05-17, ), (Cannes Film ...",114 minutes,United States,...,$6 million,$2.7 million,James Foley,Avenue Pictures,Howard E. Smith,Maurice Jarre,"[Ric Kidney, Robert Redlin]",Avenue Pictures,"[James Foley, Robert Redlin]",tt0098994
2,https://en.wikipedia.org/wiki/Air_America_(film),1990,https://www.imdb.com/title/tt0099005/,Air America,"[Air America, by, Christopher Robbins]","[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",Roger Deakins,"[August 10, 1990, (, 1990-08-10, )]",113 minutes,United States,...,$35 million,"$57,718,089",Roger Spottiswoode,TriStar Pictures,"[John Bloom, Lois Freeman-Fox]",Charles Gross,Daniel Melnick,"[Carolco Pictures, IndieProd Company]","[John Eskow, Richard Rush]",tt0099005
3,https://en.wikipedia.org/wiki/Alice_(1990_film),1990,https://www.imdb.com/title/tt0099012/,Alice,NaN,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",Carlo Di Palma,"[December 25, 1990, (, 1990-12-25, )]",106 minutes,United States,...,$12 million,"$7,331,647",Woody Allen,Orion Pictures,Susan E. Morse,NaN,Robert Greenhut,NaN,Woody Allen,tt0099012
4,https://en.wikipedia.org/wiki/Almost_an_Angel,1990,https://www.imdb.com/title/tt0099018/,Almost an Angel,NaN,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",Russell Boyd,"December 19, 1990",95 minutes,US,...,$25 million,"$6,939,946 (USA)",John Cornell,Paramount Pictures,David Stiven,Maurice Jarre,John Cornell,NaN,Paul Hogan,tt0099018

In [167]:
box_office = wiki_movies_df['Box office'].dropna()

In [168]:
# Regular expressions only work on strings,make sure all of the box office data is entered as a string.
#By using the map() method,see which values are not strings. Fmake a is_not_a_string() function:

def is_not_a_string(x):
    return type(x) != str
box_office[box_office.map(is_not_a_string)]

34                           [US$, 4,212,828]
54      [$6,698,361 (, United States, ), [2]]
74                    [$6,488,144, (US), [1]]
126                [US$1,531,489, (domestic)]
130                          [US$, 4,803,039]
                        ...
6980               [$99.6, million, [4], [5]]
6994                   [$365.6, million, [1]]
6995                         [$53.8, million]
7015                     [$435, million, [7]]
7048                   [$529.3, million, [4]]
Name: Box office, Length: 135, dtype: object

In [169]:
# stripped-down, one-line way of writing our functions: lambda functions, lambda arguments: expression
box_office[box_office.map(lambda x: type(x) != str)]

34                           [US$, 4,212,828]
54      [$6,698,361 (, United States, ), [2]]
74                    [$6,488,144, (US), [1]]
126                [US$1,531,489, (domestic)]
130                          [US$, 4,803,039]
                        ...
6980               [$99.6, million, [4], [5]]
6994                   [$365.6, million, [1]]
6995                         [$53.8, million]
7015                     [$435, million, [7]]
7048                   [$529.3, million, [4]]
Name: Box office, Length: 135, dtype: object

In [170]:
#  use a simple space as joining character and apply the join() function only when data points are lists.
box_office = box_office.apply(lambda x: ' '.join(x) if type(x) == list else x)

In [171]:
form_one = r'\$\d+\.?\d*\s*[mb]illion'

In [172]:
box_office.str.contains(form_one, flags=re.IGNORECASE, na=False).sum()

3896

In [173]:
form_two = r'\$\d{1,3}(?:,\d{3})+'
box_office.str.contains(form_two, flags=re.IGNORECASE, na=False).sum()

1544

In [174]:
matches_form_one = box_office.str.contains(form_one, flags=re.IGNORECASE, na=False)
matches_form_two = box_office.str.contains(form_two, flags=re.IGNORECASE, na=False)

In [175]:
# this will throw an error!
# box_office[(not matches_form_one) and (not matches_form_two)]
box_office[~matches_form_one & ~matches_form_two]

34                         US$ 4,212,828
79                              $335.000
110                   $4.35-4.37 million
130                        US$ 4,803,039
600                           $5000 (US)
731                         $ 11,146,270
957                             $ 50,004
1070                          35,254,617
1147    $ 407,618 (U.S.) (sub-total) [1]
1446                        $ 11,829,959
1480                          £3 million
1611                            $520.000
1865                        ¥1.1 billion
2032                                 N/A
2091                                $309
2130               US$ 171.8 million [9]
2257                   US$ 3,395,581 [1]
2263            $ 1,223,034 ( domestic )
2347                            $282.175
2638            $ 104,883 (US sub-total)
2665         926,423 admissions (France)
2697      $ 1.7 million (US) (sub-total)
2823                            $414.000
2924                            $621.000
3088           $32 [2] –33.1 million [1]
3631                                 TBA
3859                  $38.9–40.3 million
3879            CN¥3.650 million (China)
4116                          £7,385,434
4123                            $161.000
4261                  $20.7–23.9 million
4306                              $20-30
4492                        $47.7 millon
4561             $45.2k (only in Turkey)
4662                USD$ 8.2 million [2]
5362                   $ 142 million [3]
5447                               £2.56
5784                            413 733$
6013                             Unknown
6145                  $17.5–18.4 million
6234                  $41.8–41.9 million
6369                               $111k
6370                                $588
6593                      less than $372
6829                    $ 41 million [3]
6843                             8 crore
6904                         $6.9 millon
Name: Box office, dtype: object

In [176]:
form_one = r'\$\s*\d+\.?\d*\s*[mb]illion'
form_two = r'\$\s*\d{1,3}(?:,\d{3})+'

In [177]:
form_two = r'\$\s*\d{1,3}(?:[,\.]\d{3})+'

In [178]:
form_two = r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)'

In [179]:
box_office = box_office.str.replace(r'\$.*[-—–](?![a-z])', '$', regex=True)

In [180]:
form_one = r'\$\s*\d+\.?\d*\s*[mb]illi?on'

In [181]:
# Extract and Convert the Box Office Values
box_office.str.extract(f'({form_one}|{form_two})')

                  0
0     $21.4 million
1      $2.7 million
2       $57,718,089
3        $7,331,647
4        $6,939,946
...             ...
7070  $19.4 million
7071  $41.9 million
7072  $76.1 million
7073  $38.4 million
7074   $5.5 million

[5485 rows x 1 columns]

In [182]:
# need a function to turn the extracted values into a numeric value. We'll call it parse_dollars,
#parse_dollars will take in a string and return a floating-point number. 
# def parse_dollars(s):
    # if s is not a string, return NaN

    # if input is of the form $###.# million

        # remove dollar sign and " million"

        # convert to float and multiply by a million

        # return value

    # if input is of the form $###.# billion

        # remove dollar sign and " billion"

        # convert to float and multiply by a billion

        # return value

    # if input is of the form $###,###,###

        # remove dollar sign and commas

        # convert to float

        # return value

    # otherwise, return NaN

In [183]:
# use the re module to access the regular expression functions. use re.match(pattern, string)
def parse_dollars(s):
    # if s is not a string, return NaN
    if type(s) != str:
        return np.nan

    # if input is of the form $###.# million
    if re.match(r'\$\s*\d+\.?\d*\s*milli?on', s, flags=re.IGNORECASE):
        

        # remove dollar sign and " million"

        # convert to float and multiply by a million

        # return value

    # if input is of the form $###.# billion
    elif re.match(r'\$\s*\d+\.?\d*\s*billi?on', s, flags=re.IGNORECASE):

        # remove dollar sign and " billion"

        # convert to float and multiply by a billion

        # return value

    # if input is of the form $###,###,###
    elif re.match(r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)', s, flags=re.IGNORECASE):

        # remove dollar sign and commas

        # convert to float

        # return value

    # otherwise, return NaN
    else:
        return np.nan

IndentationError: expected an indented block (<ipython-input-183-e52c1685595e>, line 18)

In [ ]:
# use re.sub(pattern, replacement_string, string) to remove dollar signs, spaces, commas, and letters, if necessary.
def parse_dollars(s):
    # if s is not a string, return NaN
    if type(s) != str:
        return np.nan

    # if input is of the form $###.# million
    if re.match(r'\$\s*\d+\.?\d*\s*milli?on', s, flags=re.IGNORECASE):

        # remove dollar sign and " million"
        s = re.sub('\$|\s|[a-zA-Z]','', s)

        # convert to float and multiply by a million

        # return value

    # if input is of the form $###.# billion
    elif re.match(r'\$\s*\d+\.?\d*\s*billi?on', s, flags=re.IGNORECASE):

        # remove dollar sign and " billion"
        s = re.sub('\$|\s|[a-zA-Z]','', s)

        # convert to float and multiply by a billion

        # return value

    # if input is of the form $###,###,###
    elif re.match(r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)', s, flags=re.IGNORECASE):

        # remove dollar sign and commas
        s = re.sub('\$|,','', s)

        # convert to float

        # return value

    # otherwise, return NaN
    else:
        return np.nan

In [ ]:
# convert all the strings to floats, multiply by the right amount, and return the value.
def parse_dollars(s):
    # if s is not a string, return NaN
    if type(s) != str:
        return np.nan

    # if input is of the form $###.# million
    if re.match(r'\$\s*\d+\.?\d*\s*milli?on', s, flags=re.IGNORECASE):

        # remove dollar sign and " million"
        s = re.sub('\$|\s|[a-zA-Z]','', s)

        # convert to float and multiply by a million
        value = float(s) * 10**6

        # return value
        return value

    # if input is of the form $###.# billion
    elif re.match(r'\$\s*\d+\.?\d*\s*billi?on', s, flags=re.IGNORECASE):

        # remove dollar sign and " billion"
        s = re.sub('\$|\s|[a-zA-Z]','', s)

        # convert to float and multiply by a billion
        value = float(s) * 10**9

        # return value
        return value

    # if input is of the form $###,###,###
    elif re.match(r'\$\s*\d{1,3}(?:[,\.]\d{3})+(?!\s[mb]illion)', s, flags=re.IGNORECASE):

        # remove dollar sign and commas
        s = re.sub('\$|,','', s)

        # convert to float
        value = float(s)

        # return value
        return value

    # otherwise, return NaN
    else:
        return np.nan

In [ ]:
wiki_movies_df['box_office'] = box_office.str.extract(f'({form_one}|{form_two})', flags=re.IGNORECASE)[0].apply(parse_dollars)
wiki_movies_df['box_office']

In [ ]:
wiki_movies_df.drop('Box office', axis=1, inplace=True)

In [ ]:
# Create a budget variable 
budget = wiki_movies_df['Budget'].dropna()

In [ ]:
# Convert any lists to strings:
budget = budget.map(lambda x: ' '.join(x) if type(x) == list else x)

In [ ]:
# remove any values between a dollar sign and a hyphen (for budgets given in ranges):
budget = budget.str.replace(r'\$.*[-—–](?![a-z])', '$', regex=True)

In [ ]:
form_one = r'\$\d+\.?\d*\s*[mb]illion'
budget.str.contains(form_one, flags=re.IGNORECASE, na=False).sum()

In [ ]:
form_two = r'\$\d{1,3}(?:,\d{3})+'
budget.str.contains(form_two, flags=re.IGNORECASE, na=False).sum()

In [ ]:
matches_form_one = budget.str.contains(form_one, flags=re.IGNORECASE, na=False)
matches_form_two = budget.str.contains(form_two, flags=re.IGNORECASE, na=False)
budget[~matches_form_one & ~matches_form_two]

In [ ]:
budget = budget.str.replace(r'\[\d+\]\s*', '')
budget[~matches_form_one & ~matches_form_two]

In [ ]:
wiki_movies_df['budget'] = budget.str.extract(f'({form_one}|{form_two})', flags=re.IGNORECASE)[0].apply(parse_dollars)

In [ ]:
wiki_movies_df.drop('Budget', axis=1, inplace=True)

In [ ]:
# Parse Release Date
release_date = wiki_movies_df['Release date'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)

In [ ]:
date_form_one = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s[123]?\d,\s\d{4}'
date_form_two = r'\d{4}.[01]\d.[0123]\d'
date_form_three = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\s\d{4}'
date_form_four = r'\d{4}'

In [ ]:
# extract the dates
release_date.str.extract(f'({date_form_one}|{date_form_two}|{date_form_three}|{date_form_four})', flags=re.IGNORECASE)

In [ ]:
wiki_movies_df['release_date'] = pd.to_datetime(release_date.str.extract(f'({date_form_one}|{date_form_two}|{date_form_three}|{date_form_four})')[0], infer_datetime_format=True)

In [ ]:
# Parse Running Time
running_time = wiki_movies_df['Running time'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)

In [ ]:
running_time.str.contains(r'^\d*\s*minutes$', flags=re.IGNORECASE, na=False).sum()

In [ ]:
running_time[running_time.str.contains(r'^\d*\s*minutes$', flags=re.IGNORECASE, na=False) != True]

In [ ]:
running_time.str.contains(r'^\d*\s*m', flags=re.IGNORECASE, na=False).sum()

In [ ]:
running_time[running_time.str.contains(r'^\d*\s*m', flags=re.IGNORECASE, na=False) != True]

In [ ]:
running_time_extract = running_time.str.extract(r'(\d+)\s*ho?u?r?s?\s*(\d*)|(\d+)\s*m')

In [ ]:
# convert into numerical value
running_time_extract = running_time_extract.apply(lambda col: pd.to_numeric(col, errors='coerce')).fillna(0)

In [ ]:
wiki_movies_df['running_time'] = running_time_extract.apply(lambda row: row[0]*60 + row[1] if row[2] == 0 else row[2], axis=1)

In [ ]:
wiki_movies_df.drop('Running time', axis=1, inplace=True)

In [ ]:
kaggle_metadata.dtypes

In [ ]:
kaggle_metadata['adult'].value_counts()

In [ ]:
# Remove Bad Data
kaggle_metadata[~kaggle_metadata['adult'].isin(['True','False'])]

In [ ]:
#  keep rows where the adult column is False, and then drop the adult column.
kaggle_metadata = kaggle_metadata[kaggle_metadata['adult'] == 'False'].drop('adult',axis='columns')

In [ ]:
kaggle_metadata['video'].value_counts()

In [ ]:
kaggle_metadata['video'] == 'True'

In [ ]:
kaggle_metadata['video'] = kaggle_metadata['video'] == 'True'

In [ ]:
kaggle_metadata['budget'] = kaggle_metadata['budget'].astype(int)
kaggle_metadata['id'] = pd.to_numeric(kaggle_metadata['id'], errors='raise')
kaggle_metadata['popularity'] = pd.to_numeric(kaggle_metadata['popularity'], errors='raise')

In [ ]:
kaggle_metadata['release_date'] = pd.to_datetime(kaggle_metadata['release_date'])

In [ ]:
ratings.info(null_counts=True)

In [ ]:
pd.to_datetime(ratings['timestamp'], unit='s')

In [ ]:
ratings['timestamp'] = pd.to_datetime(ratings['timestamp'], unit='s')

In [ ]:
pd.options.display.float_format = '{:20,.2f}'.format
ratings['rating'].plot(kind='hist')
ratings['rating'].describe()

In [ ]:
movies_df = pd.merge(wiki_movies_df, kaggle_metadata, on='imdb_id', suffixes=['_wiki','_kaggle'])
movies_df.head()

In [ ]:
# Competing data:
# Wiki                     Movielens                Resolution
#--------------------------------------------------------------------------
# title_wiki               title_kaggle
# running_time             runtime
# budget_wiki              budget_kaggle
# box_office               revenue
# release_date_wiki        release_date_kaggle
# Language                 original_language
# Production company(s)    production_companies

In [ ]:
# Title
movies_df[['title_wiki','title_kaggle']]

In [ ]:
movies_df[movies_df['title_wiki'] != movies_df['title_kaggle']][['title_wiki','title_kaggle']]

In [ ]:
# Show any rows where title_kaggle is empty
movies_df[(movies_df['title_kaggle'] == '') | (movies_df['title_kaggle'].isnull())]

In [ ]:
# Competing data:
# Wiki                     Movielens                Resolution
#--------------------------------------------------------------------------
# title_wiki               title_kaggle               Drop Wikipedia.
# running_time             runtime
# budget_wiki              budget_kaggle
# box_office               revenue
# release_date_wiki        release_date_kaggle
# Language                 original_language
# Production company(s)    production_companies

In [ ]:
# Runtime
movies_df.fillna(0).plot(x='running_time', y='runtime', kind='scatter')

In [ ]:
# Competing data:
# Wiki                     Movielens                Resolution
#--------------------------------------------------------------------------
# title_wiki               title_kaggle               Drop Wikipedia.
# running_time             runtime                    Keep Kaggle; fill in zeros with Wikipedia data.
# budget_wiki              budget_kaggle
# box_office               revenue
# release_date_wiki        release_date_kaggle
# Language                 original_language
# Production company(s)    production_companies

In [ ]:
# Budget
movies_df.fillna(0).plot(x='budget_wiki',y='budget_kaggle', kind='scatter')

In [ ]:
# Competing data:
# Wiki                     Movielens                Resolution
#--------------------------------------------------------------------------
# title_wiki               title_kaggle               Drop Wikipedia.
# running_time             runtime                    Keep Kaggle; fill in zeros with Wikipedia data.
# budget_wiki              budget_kaggle              Keep Kaggle; fill in zeros with Wikipedia data.
# box_office               revenue
# release_date_wiki        release_date_kaggle
# Language                 original_language
# Production company(s)    production_companies

In [ ]:
# Box Office
movies_df.fillna(0).plot(x='box_office', y='revenue', kind='scatter')

In [ ]:
movies_df.fillna(0)[movies_df['box_office'] < 10**9].plot(x='box_office', y='revenue', kind='scatter')

In [ ]:
# Competing data:
# Wiki                     Movielens                Resolution
#--------------------------------------------------------------------------
# title_wiki               title_kaggle               Drop Wikipedia.
# running_time             runtime                    Keep Kaggle; fill in zeros with Wikipedia data.
# budget_wiki              budget_kaggle              Keep Kaggle; fill in zeros with Wikipedia data.
# box_office               revenue                    Keep Kaggle; fill in zeros with Wikipedia data.
# release_date_wiki        release_date_kaggle
# Language                 original_language
# Production company(s)    production_companies

In [ ]:
# Release Date
movies_df[['release_date_wiki','release_date_kaggle']].plot(x='release_date_wiki', y='release_date_kaggle', style='.')

In [ ]:
movies_df[(movies_df['release_date_wiki'] > '1996-01-01') & (movies_df['release_date_kaggle'] < '1965-01-01')]

In [ ]:
movies_df[(movies_df['release_date_wiki'] > '1996-01-01') & (movies_df['release_date_kaggle'] < '1965-01-01')].index

In [ ]:
movies_df = movies_df.drop(movies_df[(movies_df['release_date_wiki'] > '1996-01-01') & (movies_df['release_date_kaggle'] < '1965-01-01')].index)

In [ ]:
movies_df[movies_df['release_date_wiki'].isnull()]

In [ ]:
# Competing data:
# Wiki                     Movielens                Resolution
#--------------------------------------------------------------------------
# title_wiki               title_kaggle               Drop Wikipedia.
# running_time             runtime                    Keep Kaggle; fill in zeros with Wikipedia data.
# budget_wiki              budget_kaggle              Keep Kaggle; fill in zeros with Wikipedia data.
# box_office               revenue                    Keep Kaggle; fill in zeros with Wikipedia data.
# release_date_wiki        release_date_kaggle        Drop Wikipedia.
# Language                 original_language
# Production company(s)    production_companies

In [ ]:
# Language
movies_df['Language'].value_counts()

In [ ]:
movies_df['Language'].apply(lambda x: tuple(x) if type(x) == list else x).value_counts(dropna=False)

In [ ]:
movies_df['original_language'].value_counts(dropna=False)

In [ ]:
# Competing data:
# Wiki                     Movielens                Resolution
#--------------------------------------------------------------------------
# title_wiki               title_kaggle               Drop Wikipedia.
# running_time             runtime                    Keep Kaggle; fill in zeros with Wikipedia data.
# budget_wiki              budget_kaggle              Keep Kaggle; fill in zeros with Wikipedia data.
# box_office               revenue                    Keep Kaggle; fill in zeros with Wikipedia data.
# release_date_wiki        release_date_kaggle        Drop Wikipedia.
# Language                 original_language          Drop Wikipedia.
# Production company(s)    production_companies

In [ ]:
# Production Companies
movies_df[['Production company(s)','production_companies']]

In [ ]:
# Competing data:
# Wiki                     Movielens                Resolution
#--------------------------------------------------------------------------
# title_wiki               title_kaggle               Drop Wikipedia.
# running_time             runtime                    Keep Kaggle; fill in zeros with Wikipedia data.
# budget_wiki              budget_kaggle              Keep Kaggle; fill in zeros with Wikipedia data.
# box_office               revenue                    Keep Kaggle; fill in zeros with Wikipedia data.
# release_date_wiki        release_date_kaggle        Drop Wikipedia.
# Language                 original_language          Drop Wikipedia.
# Production company(s)    production_companies       Drop Wikipedia.

In [ ]:
 # Put It All Together
# drop the title_wiki, release_date_wiki, Language, and Production company(s) columns.
movies_df.drop(columns=['title_wiki','release_date_wiki','Language','Production company(s)'], inplace=True)

In [ ]:
# make a function that fills in missing data for a column pair and then drops the redundant column
def fill_missing_kaggle_data(df, kaggle_column, wiki_column):
    df[kaggle_column] = df.apply(
        lambda row: row[wiki_column] if row[kaggle_column] == 0 else row[kaggle_column]
        , axis=1)
    df.drop(columns=wiki_column, inplace=True)

In [ ]:
# run the function for the three column pairs to fill in zeros.

fill_missing_kaggle_data(movies_df, 'runtime', 'running_time')
fill_missing_kaggle_data(movies_df, 'budget_kaggle', 'budget_wiki')
fill_missing_kaggle_data(movies_df, 'revenue', 'box_office')
movies_df

In [184]:
# check that there aren't any columns with only one value.Don't forget to convert lists to tuples for value_counts() to work.

for col in movies_df.columns:
    lists_to_tuples = lambda x: tuple(x) if type(x) == list else x
    value_counts = movies_df[col].apply(lists_to_tuples).value_counts(dropna=False)
    num_values = len(value_counts)
    if num_values == 1:
        print(col)

video

In [185]:
movies_df['video'].value_counts(dropna=False)

False    6051
Name: video, dtype: int64

In [186]:
movies_df = movies_df.loc[:, ['imdb_id','id','title_kaggle','original_title','tagline','belongs_to_collection','url','imdb_link',
                       'runtime','budget_kaggle','revenue','release_date_kaggle','popularity','vote_average','vote_count',
                       'genres','original_language','overview','spoken_languages','Country',
                       'production_companies','production_countries','Distributor',
                       'Producer(s)','Director','Starring','Cinematography','Editor(s)','Writer(s)','Composer(s)','Based on'
                      ]]

In [188]:
movies_df.rename({'id':'kaggle_id',
                  'title_kaggle':'title',
                  'url':'wikipedia_url',
                  'budget_kaggle':'budget',
                  'release_date_kaggle':'release_date',
                  'Country':'country',
                  'Distributor':'distributor',
                  'Producer(s)':'producers',
                  'Director':'director',
                  'Starring':'starring',
                  'Cinematography':'cinematography',
                  'Editor(s)':'editors',
                  'Writer(s)':'writers',
                  'Composer(s)':'composers',
                  'Based on':'based_on'
                 }, axis='columns', inplace=True)

In [189]:
movies_df

,imdb_id,kaggle_id,title,original_title,tagline,belongs_to_collection,wikipedia_url,imdb_link,runtime,budget,...,production_countries,distributor,producers,director,starring,cinematography,editors,writers,composers,based_on
0,tt0098987,9548,The Adventures of Ford Fairlane,The Adventures of Ford Fairlane,Kojak. Columbo. Dirty Harry. Wimps.,NaN,https://en.wikipedia.org/wiki/The_Adventures_o...,https://www.imdb.com/title/tt0098987/,104.00,"49,000,000.00",...,"[{'iso_3166_1': 'US', 'name': 'United States o...",20th Century Fox,"[Steve Perry, Joel Silver]",Renny Harlin,"[Andrew Dice Clay, Wayne Newton, Priscilla Pre...",Oliver Wood,Michael Tronick,"[David Arnott, James Cappe]","[Cliff Eidelman, Yello]","[Characters, by Rex Weiner]"
1,tt0098994,25501,"After Dark, My Sweet","After Dark, My Sweet",All they risked was everything.,NaN,"https://en.wikipedia.org/wiki/After_Dark,_My_S...",https://www.imdb.com/title/tt0098994/,114.00,"6,000,000.00",...,"[{'iso_3166_1': 'US', 'name': 'United States o...",Avenue Pictures,"[Ric Kidney, Robert Redlin]",James Foley,"[Jason Patric, Rachel Ward, Bruce Dern, George...",Mark Plummer,Howard E. Smith,"[James Foley, Robert Redlin]",Maurice Jarre,"[the novel, After Dark, My Sweet, by, Jim Thom..."
2,tt0099005,11856,Air America,Air America,The few. The proud. The totally insane.,NaN,https://en.wikipedia.org/wiki/Air_America_(film),https://www.imdb.com/title/tt0099005/,112.00,"35,000,000.00",...,"[{'iso_3166_1': 'US', 'name': 'United States o...",TriStar Pictures,Daniel Melnick,Roger Spottiswoode,"[Mel Gibson, Robert Downey Jr., Nancy Travis, ...",Roger Deakins,"[John Bloom, Lois Freeman-Fox]","[John Eskow, Richard Rush]",Charles Gross,"[Air America, by, Christopher Robbins]"
3,tt0099012,8217,Alice,Alice,NaN,NaN,https://en.wikipedia.org/wiki/Alice_(1990_film),https://www.imdb.com/title/tt0099012/,102.00,"12,000,000.00",...,"[{'iso_3166_1': 'US', 'name': 'United States o...",Orion Pictures,Robert Greenhut,Woody Allen,"[Alec Baldwin, Blythe Danner, Judy Davis, Mia ...",Carlo Di Palma,Susan E. Morse,Woody Allen,NaN,NaN
4,tt0099018,25943,Almost an Angel,Almost an Angel,Who does he think he is?,NaN,https://en.wikipedia.org/wiki/Almost_an_Angel,https://www.imdb.com/title/tt0099018/,95.00,"25,000,000.00",...,"[{'iso_3166_1': 'US', 'name': 'United States o...",Paramount Pictures,John Cornell,John Cornell,"[Paul Hogan, Elias Koteas, Linda Kozlowski]",Russell Boyd,David Stiven,Paul Hogan,Maurice Jarre,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6047,tt5639354,429191,A Fantastic Woman,Una mujer fantástica,NaN,NaN,https://en.wikipedia.org/wiki/A_Fantastic_Woman,https://www.imdb.com/title/tt5639354/,104.00,NaN,...,"[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...","[Participant Media (Chile), Piffl Medien (Germ...","[Juan de Dios Larraín, Pablo Larraín]",Sebastián Lelio,"[Daniela Vega, Francisco Reyes]",Benjamín Echazarreta,Soledad Salfate,"[Sebastián Lelio, Gonzalo Maza]",Matthew Herbert,NaN
6048,tt5390066,390059,Permission,Permission,NaN,NaN,https://en.wikipedia.org/wiki/Permission_(film),https://www.imdb.com/title/tt5390066/,96.00,NaN,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",Good Deed Entertainment,"[Brian Crano, Rebecca Hall]",Brian Crano,"[Rebecca Hall, Dan Stevens, Morgan Spector, Fr...",Adam Bricker,Matt Friedman,Brian Crano,NaN,NaN
6049,tt6304162,429174,Loveless,Нелюбовь,NaN,NaN,https://en.wikipedia.org/wiki/Loveless_(film),https://www.imdb.com/title/tt6304162/,128.00,NaN,...,"[{'iso_3166_1': 'RU', 'name': 'Russia'}, {'iso...","[Sony Pictures Releasing, (Russia), [1]]","[Alexander Rodnyansky, Sergey Melkumov, Gleb F...",Andrey Zvyagintsev,"[Maryana Spivak, Aleksey Rozin, Matvey Novikov...",Mikhail Krichman,Anna Mass,"[Oleg Negin, Andrey Zvyagintsev]","[Evgueni Galperine, Sacha Galperine]",NaN
6050,tt5795086,412302,Gemini,Gemini,NaN,NaN,https://en.wikipedia.org/wiki/Gemini_(2017_film),https://www.imdb.com/title/tt5795086/,92.00,NaN,...,"[{'iso_3166_1': 'US', 'name': 'United States o...",Neon,"[Mynette Louie, Sara Murphy, Adele Romanski]",Aaron Katz,"[Lola Kirke, Zoë Kravitz, Greta Lee, Michelle ...",Andrew Reed,Aaron Katz,Aaron Katz,Keegan DeWitt,NaN
6051,tt3859310,341689,How to Talk to Girls at Parties,How to Talk to Girls at Parties,Some girls are out of this world.,NaN,https://en.wikipedia.org/wiki/How_to_Talk_to_G...,https://www.imdb.com/title/tt3859310/,102.00,NaN,...,"[{'iso_3166_1': 'US', 'name': 'United States o...","[A24, StudioCanal UK]","[Iain Canning, Howard Gertler, John Cameron Mi...",John Cameron Mitchell,"[Elle Fanning, Alex Sharp, Nicole Kidman, Ruth...",Frank G. DeMarco,Brian A. Kates,"[Philippa Goslett, John Cameron Mitchell]","[Nico Muhly, Jamie Stewart]","["", How to Talk to Girls at Parties, "", by, Ne..."